monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]
            # uncomment to get logging in your browser
            # you may have to allow bigger header sizes in your Web server configuration
            #firephp:
            #    type: firephp
            #    level: info
            #chromephp:
            #    type: chromephp
            #    level: info
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: critical
                handler: grouped
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
            grouped:
                type:    group
                members: [streamed, deduplicated]
            streamed:
                type:  stream
                path:  '%kernel.logs_dir%/%kernel.environment%.log'
                level: debug
            deduplicated:
                type: deduplication
                # the time in seconds during which duplicate entries are discarded (default: 60)
                time: 60
                handler: symfony_mailer
            symfony_mailer:
                type:       symfony_mailer
                from_email: 'no-reply@mindsolutions.app'
                to_email:   'federico.urbinelli@gmail.com'
                # or list of recipients
                # to_email:   ['dev1@example.com', 'dev2@example.com', ...]
                subject:    'An Error Occurred! %%message%%'
                level:      debug
                formatter:  monolog.formatter.html
                content_type: text/html
