dashboard:
    path: /dashboard/{_locale}
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

controllers:
    resource: ../src/Controller/
    type: annotation
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'
    exclude: '../src/Controller/AJAXController.php'

rest_api:
    resource: ../src/Controller/AJAXController.php
    type: annotation